DROP TABLE T_ATTACHMENTS IF EXISTS;
DROP TABLE T_CST_CATEGORY IF EXISTS;
DROP TABLE T_INVOICES IF EXISTS;
DROP TABLE DUAL_INVOICE_ID IF EXISTS;
DROP TABLE DUAL_ATTACHMENT_ID IF EXISTS;
DROP SEQUENCE S_INVOICE_ID IF EXISTS;
DROP SEQUENCE S_ATTACHMENT_ID IF EXISTS;

CREATE TABLE T_ATTACHMENTS (
  ID           INTEGER IDENTITY PRIMARY KEY NOT NULL,
  INVOICE_ID   INTEGER                      NOT NULL,
  NAME         VARCHAR(255)                 NOT NULL,
  FILE_NAME    VARCHAR(255)                 NOT NULL,
  MIME_TYPE    VARCHAR(255)                 NOT NULL,
  TYPE         INTEGER                      NOT NULL,
  FILE_CONTENT BLOB                         NOT NULL
);

CREATE TABLE T_CST_CATEGORY (
  ID    INTEGER IDENTITY PRIMARY KEY NOT NULL,
  NAME  VARCHAR(255)                 NOT NULL,
  DESCR VARCHAR(255)                 NOT NULL
);

CREATE TABLE T_INVOICES (
  ID                INTEGER IDENTITY PRIMARY KEY NOT NULL,
  NAME              VARCHAR(255)                 NOT NULL,
  CATEGORY_ID       INTEGER                      NOT NULL,
  DETAILS           VARCHAR(255)                 NOT NULL,
  CREATION          DATE                         NOT NULL,
  LAST_MODIFICATION DATE                         NOT NULL
);

CREATE SEQUENCE S_INVOICE_ID START WITH 10;
CREATE TABLE DUAL_INVOICE_ID (ZERO INTEGER);
INSERT INTO DUAL_INVOICE_ID VALUES(0);

CREATE SEQUENCE S_ATTACHMENT_ID START WITH 10;
CREATE TABLE DUAL_ATTACHMENT_ID (ZERO INTEGER);
INSERT INTO DUAL_ATTACHMENT_ID VALUES(0);
