CREATE TABLE T_ATTACHMENTS (
  ID           INTEGER IDENTITY PRIMARY KEY,
  INVOICE_ID   INTEGER,
  NAME         VARCHAR(255),
  FILE_NAME    VARCHAR(255),
  MIME_TYPE    VARCHAR(255),
  TYPE         INTEGER,
  FILE_CONTENT BLOB
);

CREATE TABLE T_CST_CATEGORY (
  ID    INTEGER IDENTITY PRIMARY KEY,
  NAME  VARCHAR(255),
  DESCR VARCHAR(255)
);

CREATE TABLE T_INVOICES (
  ID                INTEGER IDENTITY PRIMARY KEY,
  NAME              VARCHAR(255),
  CATEGORY_ID       INTEGER,
  DETAILS           VARCHAR(255),
  CREATION          DATE,
  LAST_MODIFICATION DATE NULL
);
