CREATE TABLE T_CST_CATEGORY (
  ID    INTEGER IDENTITY PRIMARY KEY,
  NAME  VARCHAR(255),
  DESCR VARCHAR(255)
);

INSERT INTO T_CST_CATEGORY (ID, NAME, DESCR) VALUES (123, 'CategoryName', 'CategoryDescription')
