INSERT INTO T_ATTACHMENTS (ID, INVOICE_ID, NAME, FILE_NAME, MIME_TYPE, TYPE, FILE_CONTENT) VALUES (1, 1, 'Príloha 1', 'FileName#1', 'MimeType1', 1, hextoraw('41484f4a'));
INSERT INTO T_ATTACHMENTS (ID, INVOICE_ID, NAME, FILE_NAME, MIME_TYPE, TYPE, FILE_CONTENT) VALUES (2, 1, 'Name#2', 'FileName#2', 'MimeType2', 2, hextoraw('41484f4a'));
INSERT INTO T_ATTACHMENTS (ID, INVOICE_ID, NAME, FILE_NAME, MIME_TYPE, TYPE, FILE_CONTENT) VALUES (3, 2, 'Name#3', 'FileName#3', 'MimeType3', 3, hextoraw('41484f4a'));
